name: Migrate MongoDb

on:
  push:
    branches: [main, staging]

jobs:
  migrate-mongo-production:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Install migrate-mongo
        run: echo ${{ github.ref_name }}
      - name: Install migrate-mongo
        run: npm install -g migrate-mongo
      - name: Migrate
        run: migrate-mongo up
        env:
          MONGO_URL: "${{ secrets.MONGO_URL }}"
