name: Migrate MongoDb

on:
  push:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Install migrate-mongo
        run: yarn global add migrate-mongo
      - name: Migrate
        run: migrate-mongo up
        env:
          MONGO_URL: "${{ secrets.MONGO_URL }}"
