name: Migrate MongoDb

on:
  push:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install migrate-mongo
        run: npm install -g migrate-mongo
      - name: Initialize
        run: migrate-mongo init
      - name: Migrate
        run: migrate-mongo up
        env:
          MONGO_URL: '${{ secrets.MONGO_URL }}'